sudo: required
services:
  - docker

before_install:
  - docker build -t 1997rishabhsingh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 1997rishabhsingh/docker-react npm run test
